name: attest

on:
  workflow_dispatch:
  #push:
  #  branches: [main]

jobs:
  test-attester:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Trusty Attester
        uses: puerco/setup-trusty-attest@8a21c6b49cfc4d8643fd37a53437ee118075d0f2
      - name: Trusty Attest Score
        run:
          trusty attest --predicate-only --file=predicate.json ./repos/go
      - name: Attest
        uses: actions/attest@v1
        id: attest
        with:
          subject-name: "test"
          #subject-digest: "sha256:fc7d63442527c161ea599729e3f407a3b2b6797343d931919f694e4218eb47ab"
          subject-digest: "sha256:4a80bffe07d74bece13c3b954c6463aa25b36492bdfcfc0f674381e0b43f58c9"
          predicate-type: 'https://trustydev.pkg'
          predicate-path: "predicate.json"
