name: sign-attestation

on:
  workflow_dispatch:
  #push:
  #  branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Trusty Attester
        uses: puerco/setup-trusty-attest
      - name: Trusty Attest Score
        run:
          trusty attest --predicate-only -f predicate.json .
      - name: Attest
        uses: actions/attest@v1
        id: attest
        with:
          subject-name: "test"
          subject-digest: "sha256:fc7d63442527c161ea599729e3f407a3b2b6797343d931919f694e4218eb47ab"
          predicate-type: 'https://trustydev.pkg'
          predicate-path: "predicate.json"
