name: sign-attestation

on:
  workflow_dispatch:
  #push:
  #  branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      #- name: Build and push image
      #  id: push
      #  uses: docker/build-push-action@v5.0.0
      #  with:
      #    context: .
      #    push: true
      #    tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
      - name: Attest
        uses: actions/attest@v1
        id: attest
        with:
          #subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # jakubtestorg/attestations/sha256:e3efa96133139eaf23335d6b8aace18c8db9555c026c02d1244ab61af986e181
          subject-name: "test"
          #subject-digest: ${{ GITHUB_SHA }}
          subject-digest: "sha256:e3efa96133139eaf23335d6b8aace18c8db9555c026c02d1244ab61af986e181"
          predicate-type: 'https://trustydev.pkg'
          predicate-path: "predicate.json"
          push-to-registry: true
